BEGIN;

SELECT format(
    'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD NULL',
    :'migrator_role'
)
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = :'migrator_role')
\gexec

SELECT format(
    'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD NULL',
    :'runtime_role'
)
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = :'runtime_role')
\gexec

SELECT format(
    'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD NULL',
    :'backup_role'
)
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = :'backup_role')
\gexec

ALTER ROLE :"migrator_role"
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE :"runtime_role"
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE :"backup_role"
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

COMMENT ON ROLE :"migrator_role" IS 'oink-finai:migrator:v1';
COMMENT ON ROLE :"runtime_role" IS 'oink-finai:runtime:v1';
COMMENT ON ROLE :"backup_role" IS 'oink-finai:backup:v1';

COMMIT;
